name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install deps
        run: npm i

      - name: Run PR handler
        run: node prHandler.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
