name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install deps
        run: npm install

      - name: Run PR handler
        run: node prHandler.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN2 }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.MY_GITHUB_TOKEN2 }}
#        uses: link-/PR-metadata-action@main
#        with:
#          owner: ${{ github.repository_owner }}
#          repo: ${{ github.event.repository.name }}
#          pr_number: ${{ github.event.number }}
#          token: ${{ secrets.GITHUB_TOKEN }}
